export type StarterCatalogSeed = {
  id: string;
  title: string;
  artist: string;
};

export type StarterCatalogPack = {
  id: string;
  name: string;
  description: string;
  seeds: StarterCatalogSeed[];
};

export const STARTER_CATALOG_PACKS: StarterCatalogPack[] = [
  {
    id: "es-70-80",
    name: "España · 70s y 80s",
    description: "Clásicos españoles muy reconocibles de los 70 y 80.",
    seeds: [
      { id: "es-70-80-01", title: "Un beso y una flor", artist: "Nino Bravo" },
      { id: "es-70-80-02", title: "Libre", artist: "Nino Bravo" },
      { id: "es-70-80-03", title: "Vivir así es morir de amor", artist: "Camilo Sesto" },
      { id: "es-70-80-04", title: "Eres tú", artist: "Mocedades" },
      { id: "es-70-80-05", title: "Porque te vas", artist: "Jeanette" },
      { id: "es-70-80-06", title: "A quién le importa", artist: "Alaska y Dinarama" },
      { id: "es-70-80-07", title: "Hijo de la Luna", artist: "Mecano" },
      { id: "es-70-80-08", title: "Me cuesta tanto olvidarte", artist: "Mecano" },
      { id: "es-70-80-09", title: "Mujer contra mujer", artist: "Mecano" },
      { id: "es-70-80-10", title: "Devuélveme a mi chica", artist: "Hombres G" },
      { id: "es-70-80-11", title: "Venezia", artist: "Hombres G" },
      { id: "es-70-80-12", title: "Escuela de calor", artist: "Radio Futura" },
      { id: "es-70-80-13", title: "Déjame", artist: "Los Secretos" },
      { id: "es-70-80-14", title: "La chica de ayer", artist: "Nacha Pop" },
      { id: "es-70-80-15", title: "Lobo-hombre en París", artist: "La Unión" },
      { id: "es-70-80-16", title: "En algún lugar", artist: "Duncan Dhu" },
      { id: "es-70-80-17", title: "Insurrección", artist: "El Último de la Fila" },
      { id: "es-70-80-18", title: "Amante bandido", artist: "Miguel Bosé" },
      { id: "es-70-80-19", title: "Eloise", artist: "Tino Casal" },
      { id: "es-70-80-20", title: "Camino Soria", artist: "Gabinete Caligari" },
    ],
  },
  {
    id: "es-90",
    name: "España · 90s",
    description: "Pop, rock y canción española de los 90.",
    seeds: [
      { id: "es-90-01", title: "La Flaca", artist: "Jarabe De Palo" },
      { id: "es-90-02", title: "Corazón partío", artist: "Alejandro Sanz" },
      { id: "es-90-03", title: "Amiga mía", artist: "Alejandro Sanz" },
      { id: "es-90-04", title: "Entre dos tierras", artist: "Héroes del Silencio" },
      { id: "es-90-05", title: "Maldito duende", artist: "Héroes del Silencio" },
      { id: "es-90-06", title: "Sin documentos", artist: "Los Rodríguez" },
      { id: "es-90-07", title: "Mucho mejor", artist: "Los Rodríguez" },
      { id: "es-90-08", title: "Lo echamos a suertes", artist: "Ella Baila Sola" },
      { id: "es-90-09", title: "Cuéntame al oído", artist: "La Oreja de Van Gogh" },
      { id: "es-90-10", title: "Carolina", artist: "M-Clan" },
      { id: "es-90-11", title: "So payaso", artist: "Extremoduro" },
      { id: "es-90-12", title: "La raja de tu falda", artist: "Estopa" },
      { id: "es-90-13", title: "Cómo hemos cambiado", artist: "Presuntos Implicados" },
      { id: "es-90-14", title: "Chiquilla", artist: "Seguridad Social" },
      { id: "es-90-15", title: "Es por ti", artist: "Cómplices" },
      { id: "es-90-16", title: "El roce de tu piel", artist: "Revolver" },
      { id: "es-90-17", title: "20 de abril", artist: "Celtas Cortos" },
      { id: "es-90-18", title: "Y nos dieron las diez", artist: "Joaquín Sabina" },
      { id: "es-90-19", title: "El sitio de mi recreo", artist: "Antonio Vega" },
      { id: "es-90-20", title: "Agárrate a mí María", artist: "Los Secretos" },
    ],
  },
  {
    id: "es-2000",
    name: "España · 2000s",
    description: "Pop y rock español de los 2000.",
    seeds: [
      { id: "es-2000-01", title: "Rosas", artist: "La Oreja de Van Gogh" },
      { id: "es-2000-02", title: "Puedes contar conmigo", artist: "La Oreja de Van Gogh" },
      { id: "es-2000-03", title: "Como Camarón", artist: "Estopa" },
      { id: "es-2000-04", title: "Vino tinto", artist: "Estopa" },
      { id: "es-2000-05", title: "Zapatillas", artist: "El Canto del Loco" },
      { id: "es-2000-06", title: "Besos", artist: "El Canto del Loco" },
      { id: "es-2000-07", title: "Volverá", artist: "El Canto del Loco" },
      { id: "es-2000-08", title: "Princesas", artist: "Pereza" },
      { id: "es-2000-09", title: "Lady Madrid", artist: "Pereza" },
      { id: "es-2000-10", title: "Sin ti no soy nada", artist: "Amaral" },
      { id: "es-2000-11", title: "Días de verano", artist: "Amaral" },
      { id: "es-2000-12", title: "Soldadito marinero", artist: "Fito y Fitipaldis" },
      { id: "es-2000-13", title: "Por la boca vive el pez", artist: "Fito y Fitipaldis" },
      { id: "es-2000-14", title: "Caminando por la vida", artist: "Melendi" },
      { id: "es-2000-15", title: "Con la luna llena", artist: "Melendi" },
      { id: "es-2000-16", title: "Ave María", artist: "David Bisbal" },
      { id: "es-2000-17", title: "Bulería", artist: "David Bisbal" },
      { id: "es-2000-18", title: "Sin miedo a nada", artist: "Alex Ubago" },
      { id: "es-2000-19", title: "El sol no regresa", artist: "La Quinta Estación" },
      { id: "es-2000-20", title: "Tenía tanto que darte", artist: "Nena Daconte" },
    ],
  },
  {
    id: "es-2010-20",
    name: "España · 2010s y 2020s",
    description: "Éxitos españoles recientes y universos actuales.",
    seeds: [
      { id: "es-2010-20-01", title: "Solamente tú", artist: "Pablo Alborán" },
      { id: "es-2010-20-02", title: "Sofía", artist: "Alvaro Soler" },
      { id: "es-2010-20-03", title: "Cómo te atreves", artist: "Morat" },
      { id: "es-2010-20-04", title: "Sirenas", artist: "Taburete" },
      { id: "es-2010-20-05", title: "Terriblemente cruel", artist: "Leiva" },
      { id: "es-2010-20-06", title: "Copacabana", artist: "IZAL" },
      { id: "es-2010-20-07", title: "Emborracharme", artist: "Lori Meyers" },
      { id: "es-2010-20-08", title: "Cero", artist: "Dani Martín" },
      { id: "es-2010-20-09", title: "Blanco y negro", artist: "Malú" },
      { id: "es-2010-20-10", title: "Malamente", artist: "ROSALÍA" },
      { id: "es-2010-20-11", title: "Despechá", artist: "ROSALÍA" },
      { id: "es-2010-20-12", title: "Tú me dejaste de querer", artist: "C. Tangana" },
      { id: "es-2010-20-13", title: "Vas a quedarte", artist: "Aitana" },
      { id: "es-2010-20-14", title: "Mon Amour - Remix", artist: "zzoilo" },
      { id: "es-2010-20-15", title: "Columbia", artist: "Quevedo" },
      { id: "es-2010-20-16", title: "Lo siento", artist: "Beret" },
      { id: "es-2010-20-17", title: "Soldadito de hierro", artist: "Nil Moliner" },
      { id: "es-2010-20-18", title: "Juramento eterno de sal", artist: "Alvaro de Luna" },
      { id: "es-2010-20-19", title: "Ya no quiero ná", artist: "Lola Indigo" },
      { id: "es-2010-20-20", title: "La fama", artist: "ROSALÍA" },
    ],
  },
  {
    id: "latam-classics",
    name: "Latino · clásicos",
    description: "Grandes clásicos latinoamericanos anteriores a 2010.",
    seeds: [
      { id: "latam-classics-01", title: "De música ligera", artist: "Soda Stereo" },
      { id: "latam-classics-02", title: "Persiana americana", artist: "Soda Stereo" },
      { id: "latam-classics-03", title: "Matador", artist: "Los Fabulosos Cadillacs" },
      { id: "latam-classics-04", title: "Lamento boliviano", artist: "Enanitos Verdes" },
      { id: "latam-classics-05", title: "Mariposa Tecknicolor", artist: "Fito Paez" },
      { id: "latam-classics-06", title: "Flaca", artist: "Andrés Calamaro" },
      { id: "latam-classics-07", title: "Ahora te puedes marchar", artist: "Luis Miguel" },
      { id: "latam-classics-08", title: "La incondicional", artist: "Luis Miguel" },
      { id: "latam-classics-09", title: "Suave", artist: "Luis Miguel" },
      { id: "latam-classics-10", title: "Ojalá que llueva café", artist: "Juan Luis Guerra 4.40" },
      { id: "latam-classics-11", title: "La bilirrubina", artist: "Juan Luis Guerra 4.40" },
      { id: "latam-classics-12", title: "Bachata rosa", artist: "Juan Luis Guerra 4.40" },
      { id: "latam-classics-13", title: "Como la flor", artist: "Selena" },
      { id: "latam-classics-14", title: "Conga", artist: "Gloria Estefan" },
      { id: "latam-classics-15", title: "La gota fría", artist: "Carlos Vives" },
      { id: "latam-classics-16", title: "Estoy aquí", artist: "Shakira" },
      { id: "latam-classics-17", title: "Oye mi amor", artist: "Maná" },
      { id: "latam-classics-18", title: "Rayando el sol", artist: "Maná" },
      { id: "latam-classics-19", title: "María", artist: "Ricky Martin" },
      { id: "latam-classics-20", title: "Livin' la Vida Loca", artist: "Ricky Martin" },
    ],
  },
  {
    id: "latam-2000",
    name: "Latino · 2000s",
    description: "Pop, rock y urbano latino de los 2000.",
    seeds: [
      { id: "latam-2000-01", title: "A Dios le pido", artist: "Juanes" },
      { id: "latam-2000-02", title: "La camisa negra", artist: "Juanes" },
      { id: "latam-2000-03", title: "Suerte (Whenever, Wherever)", artist: "Shakira" },
      { id: "latam-2000-04", title: "La Tortura", artist: "Shakira" },
      { id: "latam-2000-05", title: "Labios compartidos", artist: "Maná" },
      { id: "latam-2000-06", title: "Torero", artist: "Chayanne" },
      { id: "latam-2000-07", title: "Dejaría todo", artist: "Chayanne" },
      { id: "latam-2000-08", title: "Me voy", artist: "Julieta Venegas" },
      { id: "latam-2000-09", title: "Eres", artist: "Café Tacvba" },
      { id: "latam-2000-10", title: "Caraluna", artist: "Bacilos" },
      { id: "latam-2000-11", title: "Color esperanza", artist: "Diego Torres" },
      { id: "latam-2000-12", title: "Noviembre sin ti", artist: "Reik" },
      { id: "latam-2000-13", title: "Entra en mi vida", artist: "Sin Bandera" },
      { id: "latam-2000-14", title: "Atrévete-Te-Te", artist: "Calle 13" },
      { id: "latam-2000-15", title: "Gasolina", artist: "Daddy Yankee" },
      { id: "latam-2000-16", title: "Lo Que Pasó, Pasó", artist: "Daddy Yankee" },
      { id: "latam-2000-17", title: "Dale Don Dale", artist: "Don Omar" },
      { id: "latam-2000-18", title: "Rakata", artist: "Wisin & Yandel" },
      { id: "latam-2000-19", title: "Pa' Que Retozen", artist: "Tego Calderón" },
      { id: "latam-2000-20", title: "Dile", artist: "Don Omar" },
    ],
  },
  {
    id: "latam-2010-20",
    name: "Latino · 2010s y 2020s",
    description: "Éxitos latinos y urbanos de la última década.",
    seeds: [
      { id: "latam-2010-20-01", title: "Despacito", artist: "Luis Fonsi" },
      { id: "latam-2010-20-02", title: "Bailando", artist: "Enrique Iglesias" },
      { id: "latam-2010-20-03", title: "Vivir mi vida", artist: "Marc Anthony" },
      { id: "latam-2010-20-04", title: "Propuesta indecente", artist: "Romeo Santos" },
      { id: "latam-2010-20-05", title: "Mi Gente", artist: "J Balvin" },
      { id: "latam-2010-20-06", title: "Felices los 4", artist: "Maluma" },
      { id: "latam-2010-20-07", title: "Danza Kuduro", artist: "Don Omar" },
      { id: "latam-2010-20-08", title: "Taki Taki", artist: "DJ Snake" },
      { id: "latam-2010-20-09", title: "DÁKITI", artist: "Bad Bunny" },
      { id: "latam-2010-20-10", title: "Pepas", artist: "Farruko" },
      { id: "latam-2010-20-11", title: "Tití Me Preguntó", artist: "Bad Bunny" },
      { id: "latam-2010-20-12", title: "Provenza", artist: "KAROL G" },
      { id: "latam-2010-20-13", title: "Todo De Ti", artist: "Rauw Alejandro" },
      { id: "latam-2010-20-14", title: "La Bachata", artist: "Manuel Turizo" },
      { id: "latam-2010-20-15", title: "Hawái", artist: "Maluma" },
      { id: "latam-2010-20-16", title: "Yonaguni", artist: "Bad Bunny" },
      { id: "latam-2010-20-17", title: "Callaíta", artist: "Bad Bunny" },
      { id: "latam-2010-20-18", title: "Me Porto Bonito", artist: "Bad Bunny" },
      { id: "latam-2010-20-19", title: "Tusa", artist: "KAROL G" },
      { id: "latam-2010-20-20", title: "Con Altura", artist: "ROSALÍA" },
    ],
  },
  {
    id: "anglo-70-80",
    name: "Anglo · 70s y 80s",
    description: "Clásicos internacionales de los 70 y 80.",
    seeds: [
      { id: "anglo-70-80-01", title: "Dancing Queen", artist: "ABBA" },
      { id: "anglo-70-80-02", title: "Stayin' Alive", artist: "Bee Gees" },
      { id: "anglo-70-80-03", title: "September", artist: "Earth, Wind & Fire" },
      { id: "anglo-70-80-04", title: "I Will Survive", artist: "Gloria Gaynor" },
      { id: "anglo-70-80-05", title: "Don't Stop Me Now", artist: "Queen" },
      { id: "anglo-70-80-06", title: "Another One Bites The Dust", artist: "Queen" },
      { id: "anglo-70-80-07", title: "Hotel California", artist: "Eagles" },
      { id: "anglo-70-80-08", title: "Dreams", artist: "Fleetwood Mac" },
      { id: "anglo-70-80-09", title: "Superstition", artist: "Stevie Wonder" },
      { id: "anglo-70-80-10", title: "Piano Man", artist: "Billy Joel" },
      { id: "anglo-70-80-11", title: "Rocket Man", artist: "Elton John" },
      { id: "anglo-70-80-12", title: "Your Song", artist: "Elton John" },
      { id: "anglo-70-80-13", title: "Don't Stop Believin'", artist: "Journey" },
      { id: "anglo-70-80-14", title: "Livin' On A Prayer", artist: "Bon Jovi" },
      { id: "anglo-70-80-15", title: "Take on Me", artist: "a-ha" },
      { id: "anglo-70-80-16", title: "Africa", artist: "TOTO" },
      { id: "anglo-70-80-17", title: "Billie Jean", artist: "Michael Jackson" },
      { id: "anglo-70-80-18", title: "Like a Prayer", artist: "Madonna" },
      { id: "anglo-70-80-19", title: "Sweet Child O' Mine", artist: "Guns N' Roses" },
      { id: "anglo-70-80-20", title: "With Or Without You", artist: "U2" },
    ],
  },
  {
    id: "anglo-90",
    name: "Anglo · 90s",
    description: "Pop, rock y alternativo internacional de los 90.",
    seeds: [
      { id: "anglo-90-01", title: "Smells Like Teen Spirit", artist: "Nirvana" },
      { id: "anglo-90-02", title: "Wonderwall", artist: "Oasis" },
      { id: "anglo-90-03", title: "Don't Look Back In Anger", artist: "Oasis" },
      { id: "anglo-90-04", title: "Zombie", artist: "The Cranberries" },
      { id: "anglo-90-05", title: "Torn", artist: "Natalie Imbruglia" },
      { id: "anglo-90-06", title: "...Baby One More Time", artist: "Britney Spears" },
      { id: "anglo-90-07", title: "Wannabe", artist: "Spice Girls" },
      { id: "anglo-90-08", title: "I Want It That Way", artist: "Backstreet Boys" },
      { id: "anglo-90-09", title: "No Scrubs", artist: "TLC" },
      { id: "anglo-90-10", title: "Genie In a Bottle", artist: "Christina Aguilera" },
      { id: "anglo-90-11", title: "Believe", artist: "Cher" },
      { id: "anglo-90-12", title: "My Heart Will Go On", artist: "Céline Dion" },
      { id: "anglo-90-13", title: "I Don't Want to Miss a Thing", artist: "Aerosmith" },
      { id: "anglo-90-14", title: "Iris", artist: "The Goo Goo Dolls" },
      { id: "anglo-90-15", title: "Basket Case", artist: "Green Day" },
      { id: "anglo-90-16", title: "Creep", artist: "Radiohead" },
      { id: "anglo-90-17", title: "Losing My Religion", artist: "R.E.M." },
      { id: "anglo-90-18", title: "Song 2", artist: "Blur" },
      { id: "anglo-90-19", title: "What's Up?", artist: "4 Non Blondes" },
      { id: "anglo-90-20", title: "All Star", artist: "Smash Mouth" },
    ],
  },
  {
    id: "anglo-2000",
    name: "Anglo · 2000s",
    description: "Hits internacionales de los 2000.",
    seeds: [
      { id: "anglo-2000-01", title: "Mr. Brightside", artist: "The Killers" },
      { id: "anglo-2000-02", title: "Crazy In Love", artist: "Beyoncé" },
      { id: "anglo-2000-03", title: "Umbrella", artist: "Rihanna" },
      { id: "anglo-2000-04", title: "Toxic", artist: "Britney Spears" },
      { id: "anglo-2000-05", title: "Since U Been Gone", artist: "Kelly Clarkson" },
      { id: "anglo-2000-06", title: "Complicated", artist: "Avril Lavigne" },
      { id: "anglo-2000-07", title: "Sk8er Boi", artist: "Avril Lavigne" },
      { id: "anglo-2000-08", title: "Seven Nation Army", artist: "The White Stripes" },
      { id: "anglo-2000-09", title: "Sex on Fire", artist: "Kings of Leon" },
      { id: "anglo-2000-10", title: "Use Somebody", artist: "Kings of Leon" },
      { id: "anglo-2000-11", title: "Viva La Vida", artist: "Coldplay" },
      { id: "anglo-2000-12", title: "Clocks", artist: "Coldplay" },
      { id: "anglo-2000-13", title: "Fix You", artist: "Coldplay" },
      { id: "anglo-2000-14", title: "Hey Ya!", artist: "Outkast" },
      { id: "anglo-2000-15", title: "Crazy", artist: "Gnarls Barkley" },
      { id: "anglo-2000-16", title: "Poker Face", artist: "Lady Gaga" },
      { id: "anglo-2000-17", title: "Bad Romance", artist: "Lady Gaga" },
      { id: "anglo-2000-18", title: "I Gotta Feeling", artist: "The Black Eyed Peas" },
      { id: "anglo-2000-19", title: "Chasing Cars", artist: "Snow Patrol" },
      { id: "anglo-2000-20", title: "In the End", artist: "Linkin Park" },
    ],
  },
  {
    id: "anglo-2010",
    name: "Anglo · 2010s",
    description: "Hits internacionales de los 2010.",
    seeds: [
      { id: "anglo-2010-01", title: "Rolling in the Deep", artist: "Adele" },
      { id: "anglo-2010-02", title: "Someone Like You", artist: "Adele" },
      { id: "anglo-2010-03", title: "Shape of You", artist: "Ed Sheeran" },
      { id: "anglo-2010-04", title: "Perfect", artist: "Ed Sheeran" },
      { id: "anglo-2010-05", title: "Uptown Funk", artist: "Mark Ronson" },
      { id: "anglo-2010-06", title: "Just the Way You Are", artist: "Bruno Mars" },
      { id: "anglo-2010-07", title: "Locked out of Heaven", artist: "Bruno Mars" },
      { id: "anglo-2010-08", title: "Call Me Maybe", artist: "Carly Rae Jepsen" },
      { id: "anglo-2010-09", title: "Titanium", artist: "David Guetta" },
      { id: "anglo-2010-10", title: "We Found Love", artist: "Rihanna" },
      { id: "anglo-2010-11", title: "Firework", artist: "Katy Perry" },
      { id: "anglo-2010-12", title: "Shake It Off", artist: "Taylor Swift" },
      { id: "anglo-2010-13", title: "Blank Space", artist: "Taylor Swift" },
      { id: "anglo-2010-14", title: "Counting Stars", artist: "OneRepublic" },
      { id: "anglo-2010-15", title: "Radioactive", artist: "Imagine Dragons" },
      { id: "anglo-2010-16", title: "Pompeii", artist: "Bastille" },
      { id: "anglo-2010-17", title: "Somebody That I Used to Know", artist: "Gotye" },
      { id: "anglo-2010-18", title: "Take Me to Church", artist: "Hozier" },
      { id: "anglo-2010-19", title: "Wake Me Up", artist: "Avicii" },
      { id: "anglo-2010-20", title: "Shallow", artist: "Lady Gaga" },
    ],
  },
  {
    id: "anglo-2020",
    name: "Anglo · 2020s",
    description: "Hits internacionales recientes.",
    seeds: [
      { id: "anglo-2020-01", title: "Save Your Tears", artist: "The Weeknd" },
      { id: "anglo-2020-02", title: "Levitating", artist: "Dua Lipa" },
      { id: "anglo-2020-03", title: "As It Was", artist: "Harry Styles" },
      { id: "anglo-2020-04", title: "Flowers", artist: "Miley Cyrus" },
      { id: "anglo-2020-05", title: "vampire", artist: "Olivia Rodrigo" },
      { id: "anglo-2020-06", title: "good 4 u", artist: "Olivia Rodrigo" },
      { id: "anglo-2020-07", title: "drivers license", artist: "Olivia Rodrigo" },
      { id: "anglo-2020-08", title: "Anti-Hero", artist: "Taylor Swift" },
      { id: "anglo-2020-09", title: "Espresso", artist: "Sabrina Carpenter" },
      { id: "anglo-2020-10", title: "BIRDS OF A FEATHER", artist: "Billie Eilish" },
      { id: "anglo-2020-11", title: "Beautiful Things", artist: "Benson Boone" },
      { id: "anglo-2020-12", title: "Lose Control", artist: "Teddy Swims" },
      { id: "anglo-2020-13", title: "Too Sweet", artist: "Hozier" },
      { id: "anglo-2020-14", title: "APT.", artist: "ROSÉ" },
      { id: "anglo-2020-15", title: "Die With A Smile", artist: "Lady Gaga" },
      { id: "anglo-2020-16", title: "Good Luck, Babe!", artist: "Chappell Roan" },
      { id: "anglo-2020-17", title: "Please Please Please", artist: "Sabrina Carpenter" },
      { id: "anglo-2020-18", title: "TEXAS HOLD 'EM", artist: "Beyoncé" },
      { id: "anglo-2020-19", title: "STAY", artist: "The Kid LAROI" },
      { id: "anglo-2020-20", title: "Peaches", artist: "Justin Bieber" },
    ],
  },
];

export const STARTER_CATALOG_SEEDS = STARTER_CATALOG_PACKS.flatMap((pack) =>
  pack.seeds.map((seed) => ({ ...seed, packId: pack.id, packName: pack.name })),
);

export function starterCatalogSeedById(id: string) {
  return STARTER_CATALOG_SEEDS.find((seed) => seed.id === id);
}
